[package]
name = "rs-csv-reader"
version = "0.1.4"
edition = "2021"

[lib]
name = "csv_reader"
crate-type = ["cdylib"]

[dependencies]
csv = "1.2"
pyo3 = { version = "0.19", features = ["abi3-py38"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

