name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Will trigger on any tag starting with "v"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Extract version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Verify Cargo.toml version matches tag
        run: |
          CARGO_VERSION=$(grep -m 1 'version =' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          if [ "$CARGO_VERSION" != "${{ steps.version.outputs.version }}" ]; then
            echo "Error: Cargo.toml version ($CARGO_VERSION) doesn't match tag (${{ steps.version.outputs.version }})"
            exit 1
          fi
      
      - name: Build and publish
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install maturin
          maturin publish --skip-existing

